---
functional:
  - Пользователи должны иметь возможность зарегистрироваться и создать учетную запись.
  - Войти в систему с использованием своих учетных данных.
  - Просматривать список доступных задач для решения.
  - Решать задачи, вводя необходимый код.
  - Просматривать и сравнивать свои решения с решениями других пользователей.
  - Возможность соревноваться с другими игроками в реальном времени.
  - Просматривать свою статистику и рейтинг в игре.
  - Возможность играть с ботами или друзьями
non-functional:
  - Сайт должен обеспечивать быструю загрузку страниц и обработку запросов пользователя.
  - Сайт должен обеспечивать защиту данных пользователей и предотвращать несанкционированный доступ.
  - Сайт должен быть способен обрабатывать большое количество пользователей и устойчив к высокой нагрузке.
  - Код проекта должен быть чистым, хорошо структурированным и документированным для легкого понимания и поддержки.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров и обеспечивать корректную работу на них.
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Интерфейс сайта должен быть интуитивно понятным и простым в использовании для пользователей.
  - Сайт должен работать без сбоев и ошибок, обеспечивая непрерывную работу пользователей.
  - Должен способствовать взаимодействию и обмену опытом между пользователями, создавая дружественную атмосферу.
